[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "3000"

# Base de données (copiée depuis Railway PostgreSQL)
DATABASE_URL=postgresql://postgres:password@hostname:port/database

# NextAuth - OBLIGATOIRE
NEXTAUTH_SECRET=your-super-secret-key-here-32-chars-min
NEXTAUTH_URL=https://your-app-name.railway.app

# Email (optionnel)
RESEND_API_KEY=your-resend-api-key-if-needed 